/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2022-01-05 03:47:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.admin_005fItem;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class item_005fadd_005fadmin_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/ProjectWorkspace/EZEN_PROJECT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_Tea_party_yeah/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1639357123551L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>ADMIN ITEM</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("	a 	{\r\n");
      out.write("    	text-decoration: none; /* 링크의 밑줄 제거 /\r\n");
      out.write("   		color: inherit; / 링크의 색상 제거 */\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	img {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

    String checkLogin = (String) session.getAttribute("checkLogin");
    Character checkAdmin = (Character) session.getAttribute("checkAdmin");
    Character checkMember = (Character) session.getAttribute("checkMember");

      out.write("\r\n");
      out.write("	<!-- $header -->\r\n");
      out.write("	<header class=\"main_header\">\r\n");
      out.write("		<div class=\"header_title_conteiner\">\r\n");
      out.write("			<div class=\"header_title_title\">\r\n");
      out.write("				<div class=\"header_title\">\r\n");
      out.write("					<a href=\"/main\">TEA PARTY</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"header_controller_conteiner\">\r\n");
      out.write("				");

                if (checkLogin == "success" && checkMember == 'N') {
            
      out.write("\r\n");
      out.write("				<div class=\"header_controller\">\r\n");
      out.write("					<a href=\"/mypage\">MY PAGE</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header_controller\">\r\n");
      out.write("					<a href=\"/cart.pay\">MY SHOPPING</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header_controller\">\r\n");
      out.write("					<a href=\"/logout\">LOGOUT</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

                if (checkAdmin != 'N') {
            
      out.write("\r\n");
      out.write("				<div class=\"header_controller\">\r\n");
      out.write("					<a href=\"/admin.ad\">ADMIN</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

                }
            
      out.write("\r\n");
      out.write("				");

            } else {
            
      out.write("\r\n");
      out.write("				<div class=\"header_controller\">\r\n");
      out.write("					<a href=\"/join\">JOIN</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header_controller\">\r\n");
      out.write("					<a href=\"/login\">LOGIN</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

                }
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("		<!-- $section -->\r\n");
      out.write("	");
  
	if (checkLogin == "success") { 
      out.write("\r\n");
      out.write("	   \r\n");
      out.write("	<section>\r\n");
      out.write("      <div class=\"item_info_container container\">\r\n");
      out.write("        <div class=\"item_info_container_title\">\r\n");
      out.write("          <span>NEW ITEM</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"item_info_container_description\">\r\n");
      out.write("          <div class=\"item_info_container_description_img\"><img src=\"resources/img/NO_IMAGE.png\" alt=\"없음\" id=\"original\">\r\n");
      out.write("          <form action=\"addItem.ad\" method=\"post\" name=\"frm\" enctype=\"multipart/form-data\">\r\n");
      out.write("          이미지<input type=\"file\" name=\"image\" id=\"img\" onchange=\"fileChange(this)\"/>\r\n");
      out.write("          <input type=\"hidden\" name=\"item_information\">\r\n");
      out.write("          <input type=\"hidden\" name=\"cate_code\">\r\n");
      out.write("          <input type=\"hidden\" name=\"item_name\">\r\n");
      out.write("          <input type=\"hidden\" name=\"item_price\">\r\n");
      out.write("           </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item_info_container_description_text\">\r\n");
      out.write("          <textarea name=\"item_information\" placeholder=\"상품 설명\"></textarea></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item_info_container_header\">\r\n");
      out.write("          <!-- <div class=\"item_info_container_header_cord\">\r\n");
      out.write("            NEW!\r\n");
      out.write("          </div> -->\r\n");
      out.write("          <div class=\"item_info_container_header_category\">\r\n");
      out.write("           카테고리: <select id=\"selectBox\" name=\"cate_code\">\r\n");
      out.write("	<option value=\"1\">홍차</option>\r\n");
      out.write("	<option value=\"2\">허브차</option>\r\n");
      out.write("	<option value=\"3\">전통차</option>\r\n");
      out.write("	<option value=\"4\">커피</option>\r\n");
      out.write("	<option value=\"5\">티웨어</option>\r\n");
      out.write("</select>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item_info_container_header_name\">\r\n");
      out.write("            상품명: <input type=\"text\" name=\"item_name\" placeholder=\"상품명\">\r\n");
      out.write("          </div>\r\n");
      out.write("        <!-- </div>\r\n");
      out.write("        <div class=\"item_info_container_body\"> -->\r\n");
      out.write("          <div class=\"item_info_container_body_price\">\r\n");
      out.write("            가격:<input type=\"number\" name=\"item_price\" placeholder=\"가격\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item_info_container_body_count\">\r\n");
      out.write("            수량:기본 10개\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"item_info_container_btn\">\r\n");
      out.write("          <div class=\"item_info_container_btn_update\">\r\n");
      out.write("            <input type=\"button\" value=\"상품등록\" onclick=\"checkSubmit()\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- <div class=\"item_info_container_btn_delete\">\r\n");
      out.write("            <input type=\"button\" value=\"DELETE\" />\r\n");
      out.write("          </div> -->\r\n");
      out.write("          <div class=\"item_info_container_btn_cancle\">\r\n");
      out.write("            <input type=\"button\" value=\"상품 리스트\" onclick=\"location.href='itemList.ad'\"/>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  \r\n");
      out.write("    </section>\r\n");

		}else {

      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	alert(\"로그인 하셔야 합니다!\");\r\n");
      out.write("	location.href=\"/login\";\r\n");
      out.write("	</script>\r\n");
      out.write("	");

		}
	
      out.write("\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("      function checkSubmit() {\r\n");
      out.write("        var name = document.getElementsByName('item_name')[1].value;\r\n");
      out.write("        var price = document.getElementsByName('item_price')[1].value;\r\n");
      out.write("        var information = document.getElementsByName('item_information')[1].value;\r\n");
      out.write("        var img = document.getElementsByName('image')[0].value;\r\n");
      out.write("        \r\n");
      out.write("        var target = document.getElementById(\"selectBox\");\r\n");
      out.write("        var cate=target.options[target.selectedIndex].value;\r\n");
      out.write("        \r\n");
      out.write("        if(!name){\r\n");
      out.write("        	alert(\"이름을 입력하세요\");\r\n");
      out.write("        	name.focus();\r\n");
      out.write("        	return false;\r\n");
      out.write("        }\r\n");
      out.write("        if(price<=0){\r\n");
      out.write("        	alert(\"가격을 입력하세요\");\r\n");
      out.write("        	item_price.focus();\r\n");
      out.write("        	return false;\r\n");
      out.write("        }\r\n");
      out.write("        if(!information){\r\n");
      out.write("        	alert(\"정보를 입력하세요\");\r\n");
      out.write("        	information.focus();\r\n");
      out.write("        	return false;\r\n");
      out.write("        }\r\n");
      out.write("        if(!img){\r\n");
      out.write("        	alert(\"사진 파일을 저장해주세요\");\r\n");
      out.write("        	img.focus();\r\n");
      out.write("        	return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        frm.item_information.value=information;\r\n");
      out.write("        frm.cate_code.value=cate;\r\n");
      out.write("        frm.item_name.value=name;\r\n");
      out.write("        frm.item_price.value=price;\r\n");
      out.write("        frm.method = 'post';\r\n");
      out.write("        frm.submit();\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      function fileChange(change) {\r\n");
      out.write("			var reader = new FileReader();\r\n");
      out.write("			reader.onload = function(event) {\r\n");
      out.write("				var img = document.getElementById('original');\r\n");
      out.write("				img.setAttribute(\"src\", event.target.result);\r\n");
      out.write("				document.querySelector(\"div#image_container\").appendChild(img);\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("			reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("		}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/admin/admin_Item/item_add_admin_form.jsp(24,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/style.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
