/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2022-01-03 06:58:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.item;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class review_005fForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/ProjectWorkspace/EZEN_PROJECT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_Tea_party_01_03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1639357123551L));
    _jspx_dependants.put("jar:file:/D:/ProjectWorkspace/EZEN_PROJECT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_Tea_party_01_03/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>REVIEW</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/style.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("img {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea{\r\n");
      out.write("	width:100%; \r\n");
      out.write("	height:100%; \r\n");
      out.write("    resize:none;/* 크기고정 */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("input{width:80%}    \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"main_header\">\r\n");
      out.write("    <div class=\"header_title_conteiner\">\r\n");
      out.write("        <div class=\"header_title_title\">\r\n");
      out.write("            <div class=\"header_title\"><a href=\"/main\">TEA PARTY</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_controller_conteiner\">\r\n");
      out.write("            <div class=\"header_controller\">\r\n");
      out.write("                <a href=\"/mypage\">MY PAGE</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header_controller\">\r\n");
      out.write("                <a href=\"/cart.pay\">MY SHOPPING</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header_controller\">\r\n");
      out.write("                <a href=\"/logout\">LOGOUT</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("   ");
  String checkLogin = (String) session.getAttribute("checkLogin");
	if (checkLogin == "success") { 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<section>\r\n");
      out.write("      <div class=\"review_container\">\r\n");
      out.write("        <div class=\"review_container_title\">REVIEW</div>\r\n");
      out.write("        <div class=\"review_container_box\">\r\n");
      out.write("        <form action=\"reviewInsert.item\" method=\"post\" enctype=\"multipart/form-data\" name=\"frm\">\r\n");
      out.write("          <div class=\"review_container_header\">\r\n");
      out.write("            <div class=\"review_container_header_num\">New!</div>\r\n");
      out.write("            <div class=\"review_container_header_name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("            <div class=\"review_container_header_title\">제목: <input type=\"text\" name=\"r_board_sub\" ><br></div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"review_container_context\">\r\n");
      out.write("            <div class=\"review_container_context_img\"><img src=\"resources/IMG/NO_IMAGE.png\" alt=\"이미지 없음\" id=\"original\">\r\n");
      out.write("            <br><input type=\"file\" name=\"image\" id=\"img\" onchange=\"fileChange(this)\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"review_container_context_text\"><textarea name=\"r_board_content\" placeholder=\"리뷰를 작성해주세요.상품의 내용과 관련 없는 내용은 삭제될 수 있습니다.\"></textarea></div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"review_container_btn\">\r\n");
      out.write("            <input type=\"button\" value=\"리뷰작성\" onclick=\"checkSubmit()\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"item_code\">\r\n");
      out.write("      </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("	\r\n");
      out.write("	");

		} else {

      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	alert(\"로그인 하셔야 합니다!\");\r\n");
      out.write("	location.href=\"/login\";\r\n");
      out.write("	</script>\r\n");
      out.write("	");

		}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function checkSubmit() {\r\n");
      out.write("   var r_board_sub = document.getElementsByName('r_board_sub')[0].value;\r\n");
      out.write("   var r_board_content = document.getElementsByName('r_board_content')[0].value;\r\n");
      out.write("   var fileCheck = document.getElementById(\"img\").value;\r\n");
      out.write("   if(!r_board_sub){\r\n");
      out.write("    	alert(\"제목을 입력하세요.\");\r\n");
      out.write("    	r_board_sub.focus();\r\n");
      out.write("   		return false;\r\n");
      out.write("   }\r\n");
      out.write("   if(!r_board_content){\r\n");
      out.write("    	alert(\"내용을 입력하세요\");\r\n");
      out.write("    	r_board_content.focus();\r\n");
      out.write("   		return false;\r\n");
      out.write("   }\r\n");
      out.write("   if(!fileCheck){\r\n");
      out.write("	   alert(\"이미지를 꼭 넣어주세요!\");\r\n");
      out.write("	   return false;\r\n");
      out.write("   }\r\n");
      out.write("   frm.method = 'post';\r\n");
      out.write("   frm.submit();\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("function fileChange(change) {\r\n");
      out.write("	var reader = new FileReader();\r\n");
      out.write("	reader.onload = function(event) {\r\n");
      out.write("		var img = document.getElementById('original');\r\n");
      out.write("		img.setAttribute(\"src\", event.target.result);\r\n");
      out.write("		document.querySelector(\"div#image_container\").appendChild(img);\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
